const fs = require('fs');
const path = require('path');
const { NAMESPACE, MINECRAFT_COLORS, COLOR_NAMES } = require('../constants.js');
const { encodeTileId, decodeTileId, getCanonicalRotation } = require('./gen_painting_rot_tile_atlas.png.js');

// Lazy-load canonical atlas mapping from cache (generated by gen_painting_rot_tile_atlas.png.js)
const CACHE_PATH = path.join(__dirname, 'canonical_atlas_cache.json');
let CANONICAL_TO_INDEX = null; // Map: canonicalTileId -> atlas index

function loadCanonicalMapping() {
    if (CANONICAL_TO_INDEX !== null) {
        return CANONICAL_TO_INDEX; // Already loaded
    }

    if (!fs.existsSync(CACHE_PATH)) {
        throw new Error(`❌ Atlas cache not found at ${CACHE_PATH}. Run gen_painting_rot_tile_atlas.png.js first!`);
    }

    const cacheData = JSON.parse(fs.readFileSync(CACHE_PATH, 'utf8'));
    console.log(`📚 Loaded canonical atlas mapping (${cacheData.metadata.canonicalCount} tiles)`);

    // Convert back to Map for easy lookup
    CANONICAL_TO_INDEX = new Map(Object.entries(cacheData.canonicalToIndex).map(([k, v]) => [parseInt(k), v]));
    return CANONICAL_TO_INDEX;
}

/**
 * Pack 64 rotation values (0-3) + palette_count into 6 floats
 * @param {number[]} rotations - Array of 64 rotation values (0-3)
 * @param {number} paletteCount - Palette count (1-15)
 * @returns {number[]} Array of 6 packed floats
 */
function packRotations(rotations, paletteCount) {
    const rotationFloats = [];

    // Pack first 5 floats: 12 rotations each (12 × 2 bits = 24 bits)
    for (let base = 0; base < 60; base += 12) {
        let acc = 0;
        for (let k = 0; k < 12; k++) {
            acc |= (rotations[base + k] & 0x3) << (2 * k);
        }
        rotationFloats.push(acc);
    }

    // Pack final float (rotation_f5): leaves 60-63 (8 bits) + palette_count (4 bits) + unused (12 bits)
    // Layout: bits 0-1: leaf60, bits 2-3: leaf61, bits 4-5: leaf62, bits 6-7: leaf63, bits 8-11: palette_count
    let finalFloat = 0;
    finalFloat |= (rotations[60] & 0x3);           // bits 0-1
    finalFloat |= (rotations[61] & 0x3) << 2;      // bits 2-3
    finalFloat |= (rotations[62] & 0x3) << 4;      // bits 4-5
    finalFloat |= (rotations[63] & 0x3) << 6;      // bits 6-7
    finalFloat |= (paletteCount & 0xF) << 8;       // bits 8-11
    rotationFloats.push(finalFloat);

    return rotationFloats; // Length 6
}

/**
 * Build a palette of up to 15 most-frequent canonical tileIds from leaf data
 * Also returns rotation values for each leaf
 * @param {Array<{colors: number[]}>} leaves - Array of 64 leaf objects with [TL, TR, BL, BR] colors
 * @returns {Object} PalettePack with used count, palette array, packed indices, and rotations
 */
function buildPaletteWithRotation(leaves) {
    // Load canonical atlas mapping (lazy-loaded on first use)
    const canonicalToIndex = loadCanonicalMapping();

    // 1) Convert each leaf to canonical form and track rotations
    const canonicalLeaves = leaves.map(leaf => {
        const { canonical, rotation } = getCanonicalRotation(leaf.colors);
        const [TL, TR, BL, BR] = canonical;
        return {
            originalColors: leaf.colors,
            canonicalTileId: encodeTileId(TL, TR, BL, BR),
            rotation: rotation  // 0-3
        };
    });

    // 2) Count frequency of canonical tileIds
    const freq = new Map();
    for (const leaf of canonicalLeaves) {
        freq.set(leaf.canonicalTileId, (freq.get(leaf.canonicalTileId) || 0) + 1);
    }

    // 3) Take top 15 by frequency (reduced from 16 to make room for rotation data)
    const sorted = [...freq.entries()].sort((a, b) => b[1] - a[1]).slice(0, 15);
    const topCanonicalTileIds = sorted.map(([id]) => id);
    const used = topCanonicalTileIds.length;

    // 4) Map canonical tileId to palette index (0..used-1), fallback to 0
    const indexOf = new Map();
    for (let i = 0; i < used; i++) {
        indexOf.set(topCanonicalTileIds[i], i);
    }

    // 5) Convert canonicalTileIds to atlas indices for storage in properties
    const palette = topCanonicalTileIds.map(canonicalTileId => {
        const atlasIndex = canonicalToIndex.get(canonicalTileId);
        if (atlasIndex === undefined) {
            console.warn(`⚠️  Canonical tileId ${canonicalTileId} not found in atlas!`);
            return 0;
        }
        return atlasIndex; // Render controllers use atlas index
    });

    // Fill to 15 for stable property count
    while (palette.length < 15) {
        palette.push(0);
    }

    const indices = new Array(64);
    const rotations = new Array(64);
    for (let i = 0; i < 64; i++) {
        const leaf = canonicalLeaves[i];
        const idx = indexOf.has(leaf.canonicalTileId) ? indexOf.get(leaf.canonicalTileId) : 0;
        indices[i] = idx; // 0..14
        rotations[i] = leaf.rotation; // 0..3
    }

    // 6) Pack 6 nibbles per float for palette indices (LSB packing)
    const idxFloats = [];
    for (let base = 0; base < 64; base += 6) {
        let lsbAcc = 0;
        const count = Math.min(6, 64 - base);
        for (let k = 0; k < count; k++) {
            lsbAcc |= (indices[base + k] & 0xF) << (4 * k);
        }
        idxFloats.push(lsbAcc); // <= 0xFFFFFF, safe as float
    }

    // 7) Pack rotations with palette_count
    const rotationFloats = packRotations(rotations, used);

    return { used, tp: palette, idxFloats, rotationFloats };
}

/**
 * Convert a 16x16 color grid to leaf color data
 * @param {Array<Array<number>>} colorGrid - 16x16 grid of color indices (0-16)
 * @returns {Array<{colors: number[]}>} Array of 64 leaf objects with [TL, TR, BL, BR] colors
 */
function colorGridToLeaves(colorGrid) {
    const leaves = [];

    // Process 8x8 grid of 2x2 leaves
    for (let leafY = 0; leafY < 8; leafY++) {
        for (let leafX = 0; leafX < 8; leafX++) {
            const baseX = leafX * 2;
            const baseY = leafY * 2;

            // Get 2x2 colors for this leaf
            const TL = colorGrid[baseY][baseX];
            const TR = colorGrid[baseY][baseX + 1];
            const BL = colorGrid[baseY + 1][baseX];
            const BR = colorGrid[baseY + 1][baseX + 1];

            leaves.push({ colors: [TL, TR, BL, BR] });
        }
    }

    return leaves;
}

/**
 * Generate a test checkerboard pattern image
 * @returns {Array<Array<number>>} 16x16 grid of color indices
 */
function generateTestCheckerboard() {
    const grid = [];
    const color1 = COLOR_NAMES.indexOf('white');  // 0
    const color2 = COLOR_NAMES.indexOf('blue');  // 15

    for (let y = 0; y < 16; y++) {
        const row = [];
        for (let x = 0; x < 16; x++) {
            // 2x2 checkerboard pattern
            const isEven = (Math.floor(x / 2) + Math.floor(y / 2)) % 2 === 0;
            row.push(isEven ? color1 : color2);
        }
        grid.push(row);
    }

    grid[0][0] = COLOR_NAMES.indexOf('black'); // Top-left corner red for testing
    grid[15][15] = COLOR_NAMES.indexOf('blue'); // Bottom-right corner blue for testing
    grid[1][1] = COLOR_NAMES.indexOf('yellow');
    grid[2][2] = COLOR_NAMES.indexOf('red');
    grid[4][4] = COLOR_NAMES.indexOf('red');

    return grid;
}

/**
 * Generate a test gradient pattern image
 * @returns {Array<Array<number>>} 16x16 grid of color indices
 */
function generateTestGradient() {
    const grid = [];
    const colors = [
        'black', 'blue', 'purple', 'magenta',
        'red', 'orange', 'yellow', 'lime',
        'green', 'cyan', 'light_blue', 'pink',
        'light_gray', 'gray', 'brown', 'white'
    ].map(name => COLOR_NAMES.indexOf(name));

    for (let y = 0; y < 16; y++) {
        const row = [];
        for (let x = 0; x < 16; x++) {
            // Diagonal gradient
            const colorIndex = colors[(x + y) % colors.length];
            row.push(colorIndex);
        }
        grid.push(row);
    }

    return grid;
}

/**
 * Generate a test solid color image
 * @param {string|number} color - Color name or index
 * @returns {Array<Array<number>>} 16x16 grid of color indices
 */
function generateTestSolid(color = 'white') {
    const colorIndex = typeof color === 'string' ? COLOR_NAMES.indexOf(color) : color;
    const grid = [];

    for (let y = 0; y < 16; y++) {
        const row = [];
        for (let x = 0; x < 16; x++) {
            row.push(colorIndex);
        }
        grid.push(row);
    }

    return grid;
}

/**
 * Generate default property values from a color grid with rotation optimization
 * @param {Array<Array<number>>} colorGrid - 16x16 grid of color indices
 * @returns {Object} Object with default values for all properties
 */
function generateDefaultValuesWithRotation(colorGrid) {
    const leaves = colorGridToLeaves(colorGrid);
    const pack = buildPaletteWithRotation(leaves);

    const defaults = {};

    // Palette properties (15 floats, not 16)
    for (let i = 0; i < 15; i++) {
        defaults[`${NAMESPACE}:tp${i}`] = pack.tp[i];
    }

    // Packed leaf indices (11 floats)
    for (let f = 0; f < 11; f++) {
        defaults[`${NAMESPACE}:leaf_idx_f${f}`] = pack.idxFloats[f] || 0;
    }

    // Packed rotations (6 floats, includes palette_count in rotation_f5)
    for (let f = 0; f < 6; f++) {
        defaults[`${NAMESPACE}:rotation_f${f}`] = pack.rotationFloats[f] || 0;
    }

    return { defaults, pack };
}

/**
 * Generate the complete painting_rot behavior entity JSON
 * @param {string|Array} testPattern - Test pattern: 'checkerboard', 'gradient', 'solid', 16x16 color grid array, or image path
 * @returns {Object} Complete behavior entity structure
 */
async function generatePaintingRotBehaviorEntity(testPattern = 'checkerboard') {
    console.log('🎨 Generating painting_rot behavior entity with rotation optimization...');

    // Generate test image
    let colorGrid;

    // Check if testPattern is an image file path
    if (typeof testPattern === 'string' && (testPattern.endsWith('.png') || testPattern.endsWith('.jpg') || testPattern.endsWith('.jpeg'))) {
        const { imageToColorGrid } = require('./image_to_grid.js');
        console.log('🖼️  Loading image as test pattern...');
        colorGrid = await imageToColorGrid(testPattern);
    } else {
        switch (testPattern) {
            case 'checkerboard':
                colorGrid = generateTestCheckerboard();
                console.log('🔲 Using checkerboard test pattern');
                break;
            case 'gradient':
                colorGrid = generateTestGradient();
                console.log('🌈 Using gradient test pattern');
                break;
            case 'solid':
                colorGrid = generateTestSolid('red');
                console.log('🟥 Using solid red test pattern');
                break;
            default:
                if (Array.isArray(testPattern)) {
                    colorGrid = testPattern;
                    console.log('🎨 Using custom color grid');
                } else {
                    throw new Error('Invalid test pattern. Use "checkerboard", "gradient", "solid", image path (*.png, *.jpg), or provide a 16x16 color grid');
                }
        }
    }

    // Generate default property values with rotation
    const { defaults, pack } = generateDefaultValuesWithRotation(colorGrid);

    console.log(`📊 Generated palette with ${pack.used}/15 unique canonical tiles`);
    console.log(`🔄 Packed ${pack.rotationFloats.length} rotation floats (includes palette_count)`);
    console.log(`📦 Packed ${pack.idxFloats.length} index floats (${pack.idxFloats.length * 6} max indices)`);

    // Verify 24-bit safety
    const maxValue = Math.max(...pack.tp, ...pack.idxFloats, ...pack.rotationFloats);
    const is24BitSafe = maxValue <= 16777215; // 2^24 - 1
    console.log(`✅ 24-bit safety: ${is24BitSafe ? 'PASS' : 'FAIL'} (max value: ${maxValue})`);

    // Build properties object
    const properties = {};

    // NOTE: palette_count is NOT a separate property - it's packed in rotation_f5

    // Add palette properties (15 canonical tile IDs)
    for (let i = 0; i < 15; i++) {
        properties[`${NAMESPACE}:tp${i}`] = {
            "type": "int",
            "default": defaults[`${NAMESPACE}:tp${i}`],
            "range": [0, 16777215],
            "client_sync": true
        };
    }

    // Add leaf index properties
    for (let f = 0; f < 11; f++) {
        properties[`${NAMESPACE}:leaf_idx_f${f}`] = {
            "type": "int",
            "default": defaults[`${NAMESPACE}:leaf_idx_f${f}`],
            "range": [0, 16777215],
            "client_sync": true
        };
    }

    // Add rotation properties (includes palette_count in rotation_f5)
    for (let f = 0; f < 6; f++) {
        properties[`${NAMESPACE}:rotation_f${f}`] = {
            "type": "int",
            "default": defaults[`${NAMESPACE}:rotation_f${f}`],
            "range": [0, 16777215],
            "client_sync": true
        };
    }

    // Build entity structure
    const entity = {
        "format_version": "1.18.10",
        "minecraft:entity": {
            "description": {
                "identifier": `${NAMESPACE}:painting_rot`,
                "is_summonable": true,
                "is_spawnable": true,
                "is_experimental": false,
                "properties": properties
            },
            "components": {
                "minecraft:breathable": {
                    "breathes_water": true
                },
                "minecraft:physics": {
                    "has_gravity": false,
                    "has_collision": false
                },
                "minecraft:pushable": {
                    "is_pushable": false,
                    "is_pushable_by_piston": false
                },
                "minecraft:collision_box": {
                    "width": 0,
                    "height": 0
                }
            },
            "events": {}
        }
    };

    console.log(`🎯 Generated entity with ${Object.keys(properties).length} properties (32 floats exactly)`);

    return entity;
}

/**
 * Write the behavior entity file
 * @param {string} outputPath - Optional output path
 * @param {string|Array} testPattern - Test pattern for default values (can be image path)
 */
async function writeBehaviorEntityFile(outputPath = null, testPattern = 'checkerboard') {
    if (outputPath === null) {
        outputPath = path.join("behavior_packs", "PixelPaint", "entities", "t.painting_rot.behavior.json");
    }

    console.log('💾 Generating behavior entity file...');
    const entity = await generatePaintingRotBehaviorEntity(testPattern);

    // Ensure directory exists
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    // Write to file with pretty formatting
    fs.writeFileSync(outputPath, JSON.stringify(entity, null, 2));

    console.log(`🎯 Behavior entity saved: ${outputPath}`);
    console.log(`📝 Namespace: ${NAMESPACE}`);
}

/**
 * Print information about the behavior entity
 */
function printBehaviorEntityInfo() {
    console.log('\n📚 BEHAVIOR ENTITY INFO (painting_rot):');
    console.log('========================================');

    console.log('\n📊 PROPERTY SYSTEM:');
    console.log('32 total int properties (auto-converted to float in Molang):');
    console.log('  • 15 palette properties: crtrlabs_paint:tp0 through tp14 (canonical tiles)');
    console.log('  • 11 index properties: crtrlabs_paint:leaf_idx_f0 through f10 (4-bit palette indices)');
    console.log('  • 6 rotation properties: crtrlabs_paint:rotation_f0 through f5 (2-bit rotations + palette_count)');
    console.log('  • palette_count packed in rotation_f5 at bit offset 8 (NOT a separate property)');

    console.log('\n🔄 ROTATION OPTIMIZATION:');
    console.log('  • Each leaf stores rotation (0-3) = 0°, 90°, 180°, 270°');
    console.log('  • Palette stores canonical tiles only');
    console.log('  • Reduces unique tiles by 60-70% (83,521 → ~25,000-35,000)');
    console.log('  • Atlas size: 512×512 (down from 1024×1024)');

    console.log('\n🎨 TEST PATTERNS:');
    console.log('Available test patterns for default values:');
    console.log('  • checkerboard: Black and white 2×2 checkerboard');
    console.log('  • gradient: Diagonal color gradient using all 16 colors');
    console.log('  • solid: Solid red color');

    console.log('\n🔢 ENCODING SYSTEM:');
    console.log('  • 16×16 pixels → 64 leaves (8×8 grid of 2×2 tiles)');
    console.log('  • Each leaf → canonical tileId + rotation (0-3)');
    console.log('  • Build palette: top 15 most-frequent canonical tileIds');
    console.log('  • Pack leaf indices: 6 nibbles per float (4 bits each)');
    console.log('  • Pack rotations: 12 per float (2 bits each) + palette_count in last float');
    console.log('  • 24-bit safe: all values ≤ 16,777,215');

    console.log('\n📦 ROTATION_F5 SPECIAL PACKING:');
    console.log('  • Bits 0-1:   leaf 60 rotation');
    console.log('  • Bits 2-3:   leaf 61 rotation');
    console.log('  • Bits 4-5:   leaf 62 rotation');
    console.log('  • Bits 6-7:   leaf 63 rotation');
    console.log('  • Bits 8-11:  palette_count (1-15)');
    console.log('  • Bits 12-23: unused');

    console.log('\n🔗 NAMESPACE:');
    console.log(`  • All properties prefixed with: ${NAMESPACE}:`);
    console.log('  • Matches resource pack expectations');
}

// Export functions for use as module
module.exports = {
    generatePaintingRotBehaviorEntity,
    writeBehaviorEntityFile,
    printBehaviorEntityInfo,
    buildPaletteWithRotation,
    packRotations,
    colorGridToLeaves,
    generateDefaultValuesWithRotation,
    generateTestCheckerboard,
    generateTestGradient,
    generateTestSolid
};

// Example usage when run directly
if (require.main === module) {
    (async () => {
        try {
            printBehaviorEntityInfo();

            // Check for image path argument
            const args = process.argv.slice(2);
            const testPattern = args[0] || 'checkerboard';

            await writeBehaviorEntityFile(null, testPattern);
            console.log('\n🎉 Behavior entity generation completed successfully!');

            if (testPattern !== 'checkerboard' && testPattern !== 'gradient' && testPattern !== 'solid') {
                console.log('\n💡 To use an image as test pattern:');
                console.log('   node gen_painting_rot_behavior.entity.js path/to/image.png');
            }
        } catch (error) {
            console.error('❌ Error generating behavior entity:', error);
            process.exit(1);
        }
    })();
}